Added a Maven build
blooprint/blooprint-api pull request #10
Opened 2017-05-11 20:16 UTC by adamretter

Hey Dave,

This might be of interest to you or not? I wanted to have a look at your code and be able to build it myself, so I added a Maven build in this PR. Once you have installed Apache Maven, you can now just run:

```
git clone https://github.com/blooprint/whiteSocket.git
cd whiteSocket
mvn clean compile assembly
java -jar target/whiteSocket-0.1.4-SNAPSHOT-uber.jar
```

It will also produce an "app" for you with scripts for running on Windows and Mac/Linux/Unix, just run:
```
mvn clean compile package appassembler:assemble
```
You can then find the app in `target/appassembler`, it's the sort of thing you could zip up and distribute.

Anyway, might be useful for you. Also the Maven build is natively compatible with IntelliJ IDE (or NetBeans) if you use that. If you use Eclipse I think it also has Maven support but I am not familiar with it.

2017-05-11 20:29 UTC, ddaaggeett commented
This is helpful. Maven is something I haven't used willingly, though I'm sure I've used it without knowing.

I'll to dig into this to understand what you're saying and I'm sure I won't find a reason not to merge.

Forgive my lack of knowledge - am I correct in assuming this will make dev adaptation to building the whiteSocket more seamless?

Also, you made my day!  FIRST PR - WOOT WOOOOOT!!!!!

2017-05-11 20:33 UTC, adamretter commented
I am not quite sure what you are asking there, what do you mean by "dev adaptation"?

2017-05-11 20:36 UTC, ddaaggeett commented
... does this simply make developer tools like NetBeans and IntelliJ ready to build with no fuss?

2017-05-11 20:55 UTC, adamretter commented
Yes they should just work with your project now.

2017-05-12 04:32 UTC, ddaaggeett requested changes
github is becoming more and more fascinating. i just have a few considerations before moving forward.

2017-05-12 04:32 UTC, ddaaggeett commented on pom.xml
> +        <groupId>org.sonatype.oss</groupId>
@adamretter - is the [deprecation](https://github.com/sonatype/oss-parents) of this something to worry about?

2017-05-12 04:32 UTC, ddaaggeett commented on pom.xml
> +    <inceptionYear>2016</inceptionYear>
2015

2017-05-12 04:32 UTC, ddaaggeett commented on pom.xml
> +        <java.version>1.7</java.version>
1.8

2017-05-15 20:46 UTC, adamretter commented on pom.xml
> +        <groupId>org.sonatype.oss</groupId>
@ddaaggeett Hah I didn't even know it was deprecated! So nope I haven't worried about it. It seems that the alternative now is just to pull some of the settings from their pom.xml directly into your own pom.xml. I think its probably not worth worrying about just yet, can always improve that later...

2017-05-15 20:46 UTC, adamretter commented on pom.xml
> +    <inceptionYear>2016</inceptionYear>
I will fix that...

2017-05-15 20:49 UTC, adamretter commented on pom.xml
> +        <java.version>1.7</java.version>
I will fix that...

2017-05-15 20:49 UTC, adamretter commented
@ddaaggeett Okay I fixed those two issues and rebased the commit in the PR for you.

2017-05-15 22:57 UTC, ddaaggeett commented on pom.xml
> +        <groupId>org.sonatype.oss</groupId>
sounds good

2017-05-16 00:56 UTC, merged

2017-05-16 00:59 UTC, ddaaggeett commented
@adamretter 
Adam, thanks for the first pull request (ignoring my personal a while back I did just for simple testing).
I tested - it runs - awesome! This was great to play with some branching and learn about some Maven stuff. This will definitely make it better for Java developers to come aboard and use their IDE of choice. CHEERS!